const menu = [
  {
    id: 1,
    title: 'Omlet',
    category: 'Kahvalti',
    price: 54.00,
    img: './images/item-1.jpg',
    desc: `Taze gununde toplanmis yumurtalarimizla yapilir. Istege bagli olarak olarak degisebilir`,
  },
  {
    id: 2,
    title: 'Adana Kebap',
    category: 'Ana Yemek',
    price: 67.99,
    img: './images/adana.jpg',
    desc: `Adana usulu acili kendi tesislerimizde urettigimiz malzemeler ile yapilir`,
  },
  {
    id: 3,
    title: 'Milkshake',
    category: 'Soguk Icecek',
    price: 27.99,
    img: './images/item-3.jpg',
    desc: `Kendi uretimimiz olan sut ile ile hazirlanip mevsiminde toplanmis cilekler ile gununde hazirlanmis el yapimi milkshake`,
  },
  {
    id: 4,
    title: 'Serpme Kahvalti',
    category: 'Kahvalti',
    price: 140.00,
    img: './images/item-4.jpg',
    desc: `Vanin meshur serpe kahvaltisi varsayilan olarak 2 kisilik servis edilir. `,
  },
  {
    id: 5,
    title: 'Kofte',
    category: 'Ana Yemek',
    price: 55.99,
    img: './images/kofte.jpg',
    desc: `Kendi ozel baharatimizla harmanlanmis kofte ve gununde kendi uretimimiz olan ekmek ile servis edilir`,
  },
  {
    id: 6,
    title: 'Limonata',
    category: 'Soguk Icecek',
    price: 26.99,
    img: './images/limonata.jpg',
    desc: `Gununda taze ellerimizle topladigimiz gunluk sıkılmıs limonata`,
  },
  {
    id: 7,
    title: 'Tereyaginda Sucuk',
    category: 'Ara Sicak',
    price: 29.99,
    img: './images/sucuk.jpg',
    desc: `Bol baharatli tereyaginda pismis kangal sucuk`,
  },
  {
    id: 8,
    title: 'Beyti',
    category: 'Ana Yemek',
    price: 98.50,
    img: './images/beyti.jpeg',
    desc: `Mucidinden hakiki kuzu etinden yapilmis beyti. `,
  },
  {
    id: 9,
    title: 'Sicak Cikolata',
    category: 'Sicak Icecek',
    price: 23.00,
    img: './images/ciko.jpeg',
    desc: `Gercek ertilmis cikolatadan yapilmis istege bagli sutle karistirilip servis edilir`,
  },
];
export default menu;
